<?php 
/**
 * Generated by the WordPress Option Page generator
 */

class postslides {
   private $post_slides_options;

   public function __construct() {
      add_action( 'admin_menu', array( $this, 'post_slides_add_plugin_page' ) );
      add_action( 'admin_init', array( $this, 'post_slides_page_init' ) );
	 }

   public function post_slides_add_plugin_page() {
      add_options_page(
         'Post Slides', // page_title
         'Post Slides', // menu_title
         'manage_options', // capability
         'post-slide', // menu_slug
         array( $this, 'post_slides_create_admin_page' ) // function
      );
   }

   public function post_slides_create_admin_page() {
      $this->post_slides_options = get_option( 'post_slides_option_name' ); ?>

      <div class="wrap">
         <h2>Post Slides Settings</h2>         

         <form method="post" action="options.php">
            <?php
               settings_fields( 'post_slides_option_group' );
			   echo "<table><tr><td>";
               do_settings_sections( 'post-slides-admin', 'post_slides_setting_section');
			   echo "</td><td valign='top' style='margin-top:35px; display: inline-block; margin-left: 30%;'>";
			   do_settings_sections( 'post-slides-content-admin', 'post_slides_setting_content_section');
			   echo "</td></tr>
			   </table>";
               submit_button();
            ?>
         </form>
      </div>

   <?php }

   public function post_slides_page_init() {
   
      register_setting(
         'post_slides_option_group', // option_group
         'post_slides_option_name', // option_name
         array( $this, 'post_slides_sanitize' ) // sanitize_callback
      );

      add_settings_section(
         'post_slides_setting_section', // id
         'Settings', // title
         array( $this, 'post_slides_section_info' ), // callback
         'post-slides-admin' // page
      );
	  add_settings_section(
         'post_slides_setting_content_section', // id
         ' ', // title
         array( $this, 'post_slides_content_section_info' ), // callback
         'post-slides-content-admin' // page
      );  
	
      add_settings_field(
         'pause', // id
         'Slide Speed', // title
         array( $this, 'pause_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'auto_start', // id
         'Auto Start', // title
         array( $this, 'auto_start_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'enable_loop', // id
         'Enable Loop', // title
         array( $this, 'enable_loop_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'pause_on_hover', // id
         'Pause On Hover', // title
         array( $this, 'pause_on_hover_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'enable_keypress', // id
         'Enable Keypress', // title
         array( $this, 'enable_keypress_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'next_previous_controls', // id
         'Next-Previous Controls', // title
         array( $this, 'next_previous_controls_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'enable_touch', // id
         'Enable Touch', // title
         array( $this, 'enable_touch_callback' ), // callback
         'post-slides-admin', // page
         'post_slides_setting_section' // section
      );

      add_settings_field(
         'enable_drag', // id
         'Enable Drag', // title
         array( $this, 'enable_drag_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	   add_settings_field(
         'enable_title', // id
         'Enable Title', // title
         array( $this, 'enable_title_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	  add_settings_field(
         'title_word_limit', // id
         'Title Word Limit', // title
         array( $this, 'title_word_limit_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	  
	  add_settings_field(
         'enable_content', // id
         'Enable Content', // title
         array( $this, 'enable_content_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	  add_settings_field(
         'content_word_limit', // id
         'Content Word Limit', // title
         array( $this, 'content_word_limit_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	  
	  add_settings_field(
         'enable_read_more', // id
         'Enable Read More Button', // title
         array( $this, 'enable_read_more_callback' ), // callback
         'post-slides-content-admin', // page
         'post_slides_setting_content_section' // section
      );
	  
	    
   }

   public function post_slides_sanitize($input) {
      $sanitary_values = array();

      if ( isset( $input['pause'] ) ) {
         $sanitary_values['pause'] = sanitize_text_field( $input['pause'] );
      }

      if ( isset( $input['auto_start'] ) ) {
         $sanitary_values['auto_start'] = $input['auto_start'];
      }

      if ( isset( $input['enable_loop'] ) ) {
         $sanitary_values['enable_loop'] = $input['enable_loop'];
      }

      if ( isset( $input['pause_on_hover'] ) ) {
         $sanitary_values['pause_on_hover'] = $input['pause_on_hover'];
      }

      if ( isset( $input['enable_keypress'] ) ) {
         $sanitary_values['enable_keypress'] = $input['enable_keypress'];
      }

      if ( isset( $input['next_previous_controls'] ) ) {
         $sanitary_values['next_previous_controls'] = $input['next_previous_controls'];
      }

      if ( isset( $input['enable_touch'] ) ) {
         $sanitary_values['enable_touch'] = $input['enable_touch'];
      }

      if ( isset( $input['enable_drag'] ) ) {
         $sanitary_values['enable_drag'] = $input['enable_drag'];
      }
	  if ( isset( $input['enable_title'] ) ) {
         $sanitary_values['enable_title'] = $input['enable_title'];
      }
	  if ( isset( $input['enable_content'] ) ) {
         $sanitary_values['enable_content'] = $input['enable_content'];
      }
	  if ( isset( $input['enable_read_more'] ) ) {
         $sanitary_values['enable_read_more'] = $input['enable_read_more'];
      }
	  if ( isset( $input['content_word_limit'] ) ) {
         $sanitary_values['content_word_limit'] = $input['content_word_limit'];
      }
	  if ( isset( $input['title_word_limit'] ) ) {
         $sanitary_values['title_word_limit'] = $input['title_word_limit'];
      }
      return $sanitary_values;
   }

   public function post_slides_section_info() {
      
   }
	
	public function post_slides_content_section_info() {
      
   }
	
    public function pause_callback() {
      printf(
         '<input style="width:9em" class="regular-text" type="text" name="post_slides_option_name[pause]" id="pause" value="%s">',
         isset( $this->post_slides_options['pause'] ) ? esc_attr( $this->post_slides_options['pause']) : ''
      );
   }

   public function auto_start_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['auto_start'] ) && $this->post_slides_options['auto_start'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="auto_start-0"><input type="radio" name="post_slides_option_name[auto_start]" id="auto_start-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['auto_start'] ) && $this->post_slides_options['auto_start'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="auto_start-1"><input type="radio" name="post_slides_option_name[auto_start]" id="auto_start-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function enable_loop_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_loop'] ) && $this->post_slides_options['enable_loop'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_loop-0"><input type="radio" name="post_slides_option_name[enable_loop]" id="enable_loop-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_loop'] ) && $this->post_slides_options['enable_loop'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_loop-1"><input type="radio" name="post_slides_option_name[enable_loop]" id="enable_loop-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function pause_on_hover_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['pause_on_hover'] ) && $this->post_slides_options['pause_on_hover'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="pause_on_hover-0"><input type="radio" name="post_slides_option_name[pause_on_hover]" id="pause_on_hover-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['pause_on_hover'] ) && $this->post_slides_options['pause_on_hover'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="pause_on_hover-1"><input type="radio" name="post_slides_option_name[pause_on_hover]" id="pause_on_hover-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function enable_keypress_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_keypress'] ) && $this->post_slides_options['enable_keypress'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_keypress-0"><input type="radio" name="post_slides_option_name[enable_keypress]" id="enable_keypress-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_keypress'] ) && $this->post_slides_options['enable_keypress'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_keypress-1"><input type="radio" name="post_slides_option_name[enable_keypress]" id="enable_keypress-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function next_previous_controls_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['next_previous_controls'] ) && $this->post_slides_options['next_previous_controls'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="next_previous_controls-0"><input type="radio" name="post_slides_option_name[next_previous_controls]" id="next_previous_controls-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['next_previous_controls'] ) && $this->post_slides_options['next_previous_controls'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="next_previous_controls-1"><input type="radio" name="post_slides_option_name[next_previous_controls]" id="next_previous_controls-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function enable_touch_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_touch'] ) && $this->post_slides_options['enable_touch'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_touch-0"><input type="radio" name="post_slides_option_name[enable_touch]" id="enable_touch-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_touch'] ) && $this->post_slides_options['enable_touch'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_touch-1"><input type="radio" name="post_slides_option_name[enable_touch]" id="enable_touch-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function enable_drag_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_drag'] ) && $this->post_slides_options['enable_drag'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_drag-0"><input type="radio" name="post_slides_option_name[enable_drag]" id="enable_drag-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_drag'] ) && $this->post_slides_options['enable_drag'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_drag-1"><input type="radio" name="post_slides_option_name[enable_drag]" id="enable_drag-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

	public function enable_title_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_title'] ) && $this->post_slides_options['enable_title'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_title-0"><input type="radio" name="post_slides_option_name[enable_title]" id="enable_title-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_title'] ) && $this->post_slides_options['enable_title'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_title-1"><input type="radio" name="post_slides_option_name[enable_title]" id="enable_title-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }
   
   public function enable_content_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_content'] ) && $this->post_slides_options['enable_content'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_content-0"><input type="radio" name="post_slides_option_name[enable_content]" id="enable_content-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_content'] ) && $this->post_slides_options['enable_content'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_content-1"><input type="radio" name="post_slides_option_name[enable_content]" id="enable_content-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }
   
   public function content_word_limit_callback() {
      printf(
         '<input style="width:11em" class="regular-text" type="text" name="post_slides_option_name[content_word_limit]" id="content_word_limit" value="%s" placeholder="Enter numbers only">',
         isset( $this->post_slides_options['content_word_limit'] ) ? esc_attr( $this->post_slides_options['content_word_limit']) : ''
      );
   }
   public function title_word_limit_callback() {
      printf(
         '<input style="width:11em" class="regular-text" type="text" name="post_slides_option_name[title_word_limit]" id="title_word_limit" value="%s" placeholder="Enter numbers only">',
         isset( $this->post_slides_options['title_word_limit'] ) ? esc_attr( $this->post_slides_options['title_word_limit']) : ''
      );
   }
    public function enable_read_more_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['enable_content'] ) && $this->post_slides_options['enable_read_more'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_read_more-0"><input type="radio" name="post_slides_option_name[enable_read_more]" id="enable_read_more-0" value="true" <?php echo $checked; ?>> True</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <?php $checked = ( isset( $this->post_slides_options['enable_read_more'] ) && $this->post_slides_options['enable_read_more'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_read_more-1"><input type="radio" name="post_slides_option_name[enable_read_more]" id="enable_read_more-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }
   
 }
if ( is_admin() )
   $post_slides = new postslides();
?>